[WIP] - Consistent training and test sets + removes tf-torch differences
arunraja-hub/Preference_Extraction pull request #42
Opened 2020-12-24 11:48 UTC by ricvolpe

2020-12-25 23:14 UTC, wichersn requested changes

2020-12-26 09:45 UTC, ricvolpe commented on extractors/configs/hptuning_config_tf_baseline.yaml
> -      - parameterName: gin_bindings=tf_extractor.cnn_from_obs.reg_amount
I am removing it because the Torch code does not have it and I understood that we decided to remove all differences between TF and Torch in favour of Torch.
Also, it did not seem very useful when I looked at the values that led to good perfomance. For example this is an analysis of regularization values (x-axis) and test auc (y-axis) for the fine tuning technique in TF:
[
![Screen Shot 2020-12-26 at 10 36 13](https://user-images.githubusercontent.com/24500682/103149038-323c9700-4766-11eb-98ed-67046c872ac3.png)
](url)

2020-12-26 09:45 UTC, ricvolpe commented on extractors/configs/hptuning_config_torch_baseline.yaml
> -      - parameterName: gin_bindings=TorchExtractor.weight_decay
I looked into this and weight decay seemed not useful at all. See below an analysis of weight decay values (x-axis) and test auc (y-axis) for both the subnetwork (above) and torch baseline (below) techniques.
![Screen Shot 2020-12-26 at 10 37 15](https://user-images.githubusercontent.com/24500682/103149067-77f95f80-4766-11eb-996e-890952cf4e30.png)

What do you think?

2020-12-26 23:43 UTC, wichersn approved these changes

2020-12-27 09:42 UTC, merged